import type { Currency, CurrencyConfig } from './types'
export const CURRENCY_CONFIG: Record<Currency, CurrencyConfig> = {
  EUR: {
    symbol: '€',
    code: 'EUR',
    name: 'Euro',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  GBP: {
    symbol: '£',
    code: 'GBP',
    name: 'British Pound',
    region: 'Europe',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  HUF: {
    symbol: 'Ft',
    code: 'HUF',
    name: 'Hungarian Forint',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 0,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  CHF: {
    symbol: 'CHF',
    code: 'CHF',
    name: 'Swiss Franc',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: "'",
    decimalSeparator: '.',
  },
  SEK: {
    symbol: 'kr',
    code: 'SEK',
    name: 'Swedish Krona',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  NOK: {
    symbol: 'kr',
    code: 'NOK',
    name: 'Norwegian Krone',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  DKK: {
    symbol: 'kr',
    code: 'DKK',
    name: 'Danish Krone',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  PLN: {
    symbol: 'zł',
    code: 'PLN',
    name: 'Polish Złoty',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  CZK: {
    symbol: 'Kč',
    code: 'CZK',
    name: 'Czech Koruna',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  RON: {
    symbol: 'lei',
    code: 'RON',
    name: 'Romanian Leu',
    region: 'Europe',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  USD: {
    symbol: '$',
    code: 'USD',
    name: 'US Dollar',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  CAD: {
    symbol: '$',
    code: 'CAD',
    name: 'Canadian Dollar',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  MXN: {
    symbol: '$',
    code: 'MXN',
    name: 'Mexican Peso',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  BRL: {
    symbol: 'R$',
    code: 'BRL',
    name: 'Brazilian Real',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  ARS: {
    symbol: '$',
    code: 'ARS',
    name: 'Argentine Peso',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  CLP: {
    symbol: '$',
    code: 'CLP',
    name: 'Chilean Peso',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  COP: {
    symbol: '$',
    code: 'COP',
    name: 'Colombian Peso',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  PEN: {
    symbol: 'S/',
    code: 'PEN',
    name: 'Peruvian Sol',
    region: 'Americas',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  JPY: {
    symbol: '¥',
    code: 'JPY',
    name: 'Japanese Yen',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  CNY: {
    symbol: '¥',
    code: 'CNY',
    name: 'Chinese Yuan',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  HKD: {
    symbol: 'HK$',
    code: 'HKD',
    name: 'Hong Kong Dollar',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  KRW: {
    symbol: '₩',
    code: 'KRW',
    name: 'South Korean Won',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 0,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  SGD: {
    symbol: '$',
    code: 'SGD',
    name: 'Singapore Dollar',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  INR: {
    symbol: '₹',
    code: 'INR',
    name: 'Indian Rupee',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  THB: {
    symbol: '฿',
    code: 'THB',
    name: 'Thai Baht',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  MYR: {
    symbol: 'RM',
    code: 'MYR',
    name: 'Malaysian Ringgit',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  IDR: {
    symbol: 'Rp',
    code: 'IDR',
    name: 'Indonesian Rupiah',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 0,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
  PHP: {
    symbol: '₱',
    code: 'PHP',
    name: 'Philippine Peso',
    region: 'Asia',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  AED: {
    symbol: 'د.إ',
    code: 'AED',
    name: 'UAE Dirham',
    region: 'Middle East and Africa',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  SAR: {
    symbol: '﷼',
    code: 'SAR',
    name: 'Saudi Riyal',
    region: 'Middle East and Africa',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  ILS: {
    symbol: '₪',
    code: 'ILS',
    name: 'Israeli New Shekel',
    region: 'Middle East and Africa',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  ZAR: {
    symbol: 'R',
    code: 'ZAR',
    name: 'South African Rand',
    region: 'Middle East and Africa',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: '.',
  },
  AUD: {
    symbol: '$',
    code: 'AUD',
    name: 'Australian Dollar',
    region: 'Oceania',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  NZD: {
    symbol: '$',
    code: 'NZD',
    name: 'New Zealand Dollar',
    region: 'Oceania',
    position: 'before',
    decimalPlaces: 2,
    thousandsSeparator: ',',
    decimalSeparator: '.',
  },
  RUB: {
    symbol: '₽',
    code: 'RUB',
    name: 'Russian Ruble',
    region: 'Other',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: ' ',
    decimalSeparator: ',',
  },
  TRY: {
    symbol: '₺',
    code: 'TRY',
    name: 'Turkish Lira',
    region: 'Other',
    position: 'after',
    decimalPlaces: 2,
    thousandsSeparator: '.',
    decimalSeparator: ',',
  },
}
export function formatCurrency(currency: Currency, amount: number): string {
  const config = CURRENCY_CONFIG[currency]
  let formatted: string
  if (config.decimalPlaces === 0 || Number.isInteger(amount)) {
    formatted = Math.round(amount).toString()
    formatted = formatted.replace(/\B(?=(\d{3})+(?!\d))/g, config.thousandsSeparator)
  } else {
    const parts = amount.toFixed(config.decimalPlaces).split('.')
    const integerPart = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, config.thousandsSeparator)
    const decimalPart = parts[1]
    formatted = `${integerPart}${config.decimalSeparator}${decimalPart}`
  }
  if (config.position === 'before') {
    return `${config.symbol}${formatted}`
  } else {
    return `${formatted} ${config.symbol}`
  }
}
export function getCurrencyConfig(currency: Currency): CurrencyConfig {
  return CURRENCY_CONFIG[currency]
}
export function getSupportedCurrencies(): Currency[] {
  return Object.keys(CURRENCY_CONFIG) as Currency[]
}
export function getCurrenciesByRegion(region: CurrencyConfig['region']): Currency[] {
  return (Object.entries(CURRENCY_CONFIG) as [Currency, CurrencyConfig][])
    .filter(([_, config]) => config.region === region)
    .map(([code]) => code)
}
